---
name: core
attachments:
  /: pantheon-core/root/
  boot/: pantheon-bios/pantheon-bios/images/
  /tmp: pantheon-core/tmp/
  /lib: pantheon-core/lib/
  /etc: pantheon-core/etc/
  /bin: pantheon-core/bin/
mountfile: |
  local attachments = {['/']='pantheon-core/root/',['/etc']='pantheon-core/etc/',['/bin']='pantheon-core/bin/',['/lib']='pantheon-core/lib/',['/tmp']='pantheon-core/tmp/',['boot/']='pantheon-bios/pantheon-bios/images/',}
  if not mounter then
    error("Not running in CraftOS-PC", 2)
  end
  for inside, outside in pairs(attachments) do
    -- readonly mode not supported from cosrun
    if (inside ~= "/") and (inside ~= "/rom") and (inside ~= "bios.lua") then
      mounter.mount(inside, outside, false)
    end
  end
...
